import { Destination, DestinationMeta, DayItinerary } from '@/src/types';

export const EUR_10D_META: DestinationMeta = {
  id: 'europe/western-capitals-10d',
  code: 'EUR-10D',
  cityName: 'London • Paris • Amsterdam',
  country: 'europe',
  countryName: 'Western Europe',
  region: 'Europe',
  flagEmoji: '🇪🇺',
  routeSummary: 'London ➔ Paris ➔ Amsterdam via High-Speed Rail',
  title: '10 Days in Western Europe',
  badge: 'High-Speed Rail • 3 Iconic Capitals',
  subtitle: 'Westminster, Le Marais & Jordaan Canals by Eurostar',
  description:
    'A seamless 10-day rail journey connecting London, Paris, and Amsterdam. Optimized for walking neighborhoods, world-class museums, historic canal walks, and high-speed train connections.',
  totalDays: 10,
  totalStops: 24,
};

export const EUR_10D_DAYS: DayItinerary[] = [
  // --- LONDON (DAYS 1-3) ---
  {
    id: 'day-1',
    dayNumber: 1,
    city: 'London',
    country: 'United Kingdom',
    date: 'Day 1',
    title: 'Royal Westminster & The Thames Embankment',
    subtitle: 'Parliament, Abbey & South Bank Golden Hour',
    badge: 'London • Westminster Core',
    color: '#1d4ed8', // blue-700
    polylineColor: '#1d4ed8',
    center: { lat: 51.5033, lng: -0.1195 },
    zoom: 14,
    googleMapsDirectionsUrl: 'https://www.google.com/maps/dir/?api=1&origin=Westminster+Abbey&destination=London+Eye',
    places: [
      {
        id: 'eur-d1-p1',
        number: 1,
        globalNumber: 1,
        name: 'Westminster Abbey & Elizabeth Tower (Big Ben)',
        time: '09:00 – 11:30',
        description: 'Begin beneath the Gothic towers of Westminster Abbey before walking across Parliament Square for postcard views of Big Ben along Westminster Bridge.',
        area: 'Westminster',
        coordinates: { lat: 51.4993, lng: -0.1273 },
        photo: {
          url: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=1200&q=80',
          caption: 'Big Ben and Westminster Bridge glowing in the morning Thames light',
          category: 'Architecture',
          photoTip: 'Walk halfway across Westminster Bridge on the south pavement for clean views of the clock tower.',
          credit: 'Unsplash / Travel Chronicle',
        },
        tags: [
          { text: 'Gothic Landmark', type: 'highlight' },
          { text: 'District / Circle Line', type: 'default' },
        ],
      },
      {
        id: 'eur-d1-p2',
        number: 2,
        globalNumber: 2,
        name: 'South Bank & Tate Modern Turbine Hall',
        time: '13:00 – 15:30',
        description: 'Stroll along the pedestrian-only Queens Walk past street buskers and food kiosks, entering the cavernous industrial turbine hall of Tate Modern.',
        area: 'Bankside',
        coordinates: { lat: 51.5076, lng: -0.0994 },
        photo: {
          url: 'https://images.unsplash.com/photo-1529655683826-aba9b3e77383?auto=format&fit=crop&w=1200&q=80',
          caption: 'Modern riverside culture and Millennium Bridge crossing toward St Pauls',
          category: 'Culture',
          photoTip: 'Head to Level 10 of the Blavatnik Building for panoramic 360-degree London skyline views.',
          credit: 'Unsplash / London Arts',
        },
        tags: [
          { text: 'Free Entry', type: 'highlight' },
          { text: 'Riverside Walk', type: 'default' },
        ],
      },
      {
        id: 'eur-d1-p3',
        number: 3,
        globalNumber: 3,
        name: 'Borough Market Twilight Grazing',
        time: '17:30 – 19:30',
        description: 'London’s premier artisanal food market beneath Victorian railway arches. Sample sourdough toasties, salt beef bagels, and fresh oysters.',
        area: 'London Bridge',
        coordinates: { lat: 51.5055, lng: -0.0910 },
        photo: {
          url: 'https://images.unsplash.com/photo-1533929736458-ca588d08c8be?auto=format&fit=crop&w=1200&q=80',
          caption: 'Historic railway arcade bustling with culinary artisans and food stalls',
          category: 'Culinary',
          photoTip: 'Arrive right before 6 PM when hot food stalls serve their evening specials.',
          credit: 'Unsplash / Borough Food',
        },
        tags: [
          { text: 'Artisanal Food', type: 'highlight' },
          { text: 'London Bridge Station', type: 'default' },
        ],
      },
    ],
  },
  {
    id: 'day-2',
    dayNumber: 2,
    city: 'London',
    country: 'United Kingdom',
    date: 'Day 2',
    title: 'Bloomsbury Antiquities & West End Alleys',
    subtitle: 'British Museum, Covent Garden & Seven Dials',
    badge: 'London • Heritage & Theatre',
    color: '#1d4ed8',
    polylineColor: '#1d4ed8',
    center: { lat: 51.5165, lng: -0.1260 },
    zoom: 14,
    googleMapsDirectionsUrl: 'https://www.google.com/maps/dir/?api=1&origin=British+Museum&destination=Seven+Dials',
    places: [
      {
        id: 'eur-d2-p1',
        number: 1,
        globalNumber: 4,
        name: 'British Museum & Great Court Glass Roof',
        time: '10:00 – 13:00',
        description: 'Stand inside Norman Foster’s tessellated glass Great Court and discover world history from the Rosetta Stone to ancient sculpture.',
        area: 'Bloomsbury',
        coordinates: { lat: 51.5194, lng: -0.1270 },
        photo: {
          url: 'https://images.unsplash.com/photo-1582561424760-0321d75e81fa?auto=format&fit=crop&w=1200&q=80',
          caption: 'The sweeping geometric glass canopy spanning Norman Foster’s Great Court',
          category: 'Architecture',
          photoTip: 'Stand on the north rotunda staircase to capture the diagonal geometry of the glass ceiling.',
          credit: 'Unsplash / Architecture',
        },
        tags: [
          { text: 'World Heritage', type: 'highlight' },
          { text: 'Tottenham Court Rd', type: 'default' },
        ],
      },
      {
        id: 'eur-d2-p2',
        number: 2,
        globalNumber: 5,
        name: 'Seven Dials & Neal’s Yard Secret Courtyard',
        time: '14:30 – 17:00',
        description: 'Vibrant kaleidoscope alleyway filled with independent cheese mongers, micro-bakeries, and color-drenched brick shophouses tucked away from Covent Garden.',
        area: 'Covent Garden',
        coordinates: { lat: 51.5143, lng: -0.1265 },
        photo: {
          url: 'https://images.unsplash.com/photo-1520986606214-8b456906c813?auto=format&fit=crop&w=1200&q=80',
          caption: 'Colorful painted brickwork and lush potted ferns inside secret Neal’s Yard',
          category: 'Atmosphere',
          photoTip: 'Enter via Short’s Gardens alley for the sudden dramatic color reveal.',
          credit: 'Unsplash / Covent Garden',
        },
        tags: [
          { text: 'Hidden Courtyard', type: 'highlight' },
          { text: 'Specialty Coffee', type: 'default' },
        ],
      },
    ],
  },
  {
    id: 'day-3',
    dayNumber: 3,
    city: 'London',
    country: 'United Kingdom',
    date: 'Day 3',
    title: 'Historic Fortress & Shoreditch Creative District',
    subtitle: 'Tower Bridge, Brick Lane & Street Art',
    badge: 'London • Maritime & East End',
    color: '#1d4ed8',
    polylineColor: '#1d4ed8',
    center: { lat: 51.5120, lng: -0.0760 },
    zoom: 14,
    googleMapsDirectionsUrl: 'https://www.google.com/maps/dir/?api=1&origin=Tower+Bridge&destination=Brick+Lane',
    places: [
      {
        id: 'eur-d3-p1',
        number: 1,
        globalNumber: 6,
        name: 'Tower of London & Victorian Tower Bridge',
        time: '09:30 – 12:00',
        description: 'Explore William the Conqueror’s 11th-century White Tower, then walk across the upper high-level walkways of iconic Tower Bridge.',
        area: 'Tower Hill',
        coordinates: { lat: 51.5055, lng: -0.0754 },
        photo: {
          url: 'https://images.unsplash.com/photo-1505761671935-60b3a7427bad?auto=format&fit=crop&w=1200&q=80',
          caption: 'Tower Bridge framed against the sunrise reflection along the River Thames',
          category: 'Architecture',
          photoTip: 'Position yourself on the Southwark riverside path for an unhindered angle of both suspension towers.',
          credit: 'Unsplash / Tower Bridge',
        },
        tags: [
          { text: 'Victorian Icon', type: 'highlight' },
          { text: 'Tower Hill Tube', type: 'default' },
        ],
      },
      {
        id: 'eur-d3-p2',
        number: 2,
        globalNumber: 7,
        name: 'Brick Lane Vintage & Spitalfields Market',
        time: '14:00 – 18:00',
        description: 'Immerse yourself in East London’s creative counterculture: retro vinyl basements, famous Beigel Bake salt beef, and world-renowned street art.',
        area: 'Shoreditch',
        coordinates: { lat: 51.5209, lng: -0.0718 },
        photo: {
          url: 'https://images.unsplash.com/photo-1549144511-f099e773c147?auto=format&fit=crop&w=1200&q=80',
          caption: 'Cobblestoned East End streetscapes lined with retro shops and mural art',
          category: 'Culture',
          photoTip: 'Explore Hanbury Street to photograph curated murals by global street artists.',
          credit: 'Unsplash / East End',
        },
        tags: [
          { text: 'Street Art', type: 'highlight' },
          { text: 'Salt Beef Beigel', type: 'default' },
        ],
      },
    ],
  },

  // --- TRANSIT ➔ PARIS (DAY 4) ---
  {
    id: 'day-4',
    dayNumber: 4,
    city: 'Transit ➔ Paris',
    country: 'United Kingdom / France',
    date: 'Day 4',
    title: 'High-Speed Eurostar Under the Channel ➔ Paris',
    subtitle: 'St Pancras International to Gare du Nord & Montmartre',
    badge: 'Transit • Channel Tunnel Rail',
    color: '#059669', // emerald-600
    polylineColor: '#059669',
    center: { lat: 48.8867, lng: 2.3431 },
    zoom: 13,
    googleMapsDirectionsUrl: 'https://www.google.com/maps/dir/?api=1&origin=Gare+du+Nord&destination=Sacré-Cœur',
    places: [
      {
        id: 'eur-d4-p1',
        number: 1,
        globalNumber: 8,
        name: 'Eurostar Departure: St Pancras International',
        time: '09:30 – 13:00',
        description: 'Board the 300 km/h Eurostar through the Channel Tunnel, arriving at Paris Gare du Nord in just 2 hours and 16 minutes with zero airport hassle.',
        area: 'King’s Cross / Transit',
        coordinates: { lat: 51.5314, lng: -0.1261 },
        photo: {
          url: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=1200&q=80',
          caption: 'High-speed train platforms beneath the grand Victorian ironwork of St Pancras',
          category: 'Architecture',
          photoTip: 'Arrive 75 mins early for smooth French border passport clearance on UK soil.',
          credit: 'Unsplash / Eurostar Transit',
        },
        tags: [
          { text: 'High-Speed Rail', type: 'highlight' },
          { text: 'No Airport Stress', type: 'default' },
        ],
      },
      {
        id: 'eur-d4-p2',
        number: 2,
        globalNumber: 9,
        name: 'Montmartre Sunset & Basilique du Sacré-Cœur',
        time: '17:30 – 20:30',
        description: 'Climb the travertine limestone stairs of Montmartre hilltop to watch the entire Paris basin glow pink as dusk settles over Haussmannian rooftops.',
        area: 'Montmartre, Paris',
        coordinates: { lat: 48.8867, lng: 2.3431 },
        photo: {
          url: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=80',
          caption: 'Golden evening light kissing the domes of Sacré-Cœur overlooking Paris',
          category: 'Nature & Skyline',
          photoTip: 'Sit on the lawns just below the upper terrace to avoid crowds and hear local acoustic musicians.',
          credit: 'Unsplash / Paris Skylines',
        },
        tags: [
          { text: 'Panoramic Vista', type: 'highlight' },
          { text: 'Anvers Metro', type: 'default' },
        ],
      },
    ],
  },

  // --- PARIS (DAYS 5-7) ---
  {
    id: 'day-5',
    dayNumber: 5,
    city: 'Paris',
    country: 'France',
    date: 'Day 5',
    title: 'Grand Louvre, Palais-Royal & Le Marais',
    subtitle: 'Classic Art, Glass Pyramids & Shophouse Cafés',
    badge: 'Paris • Heritage & Art',
    color: '#dc2626', // red-600
    polylineColor: '#dc2626',
    center: { lat: 48.8606, lng: 2.3376 },
    zoom: 14,
    googleMapsDirectionsUrl: 'https://www.google.com/maps/dir/?api=1&origin=Musée+du+Louvre&destination=Place+des+Vosges',
    places: [
      {
        id: 'eur-d5-p1',
        number: 1,
        globalNumber: 10,
        name: 'Musée du Louvre & I.M. Pei Pyramid',
        time: '09:00 – 13:00',
        description: 'Explore the grandest palace-museum in the world. Walk from the Winged Victory of Samothrace and Venus de Milo through the Napoleon III apartments.',
        area: '1st Arrondissement',
        coordinates: { lat: 48.8606, lng: 2.3376 },
        photo: {
          url: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?auto=format&fit=crop&w=1200&q=80',
          caption: 'I.M. Pei’s geometric glass pyramid mirrored in courtyard fountains at the Louvre',
          category: 'Architecture',
          photoTip: 'Enter via the Porte des Lions wing to bypass the primary queue at the central pyramid.',
          credit: 'Unsplash / Louvre Arts',
        },
        tags: [
          { text: 'Masterpiece Collection', type: 'highlight' },
          { text: 'Palais Royal Metro', type: 'default' },
        ],
      },
      {
        id: 'eur-d5-p2',
        number: 2,
        globalNumber: 11,
        name: 'Jardin du Palais-Royal & Buren Columns',
        time: '14:30 – 16:00',
        description: 'A serene enclosed garden bordered by 18th-century arcades, vintage bookstores, and Daniel Buren’s striped modern sculpture columns.',
        area: 'Palais-Royal',
        coordinates: { lat: 48.8638, lng: 2.3371 },
        photo: {
          url: 'https://images.unsplash.com/photo-1471623817296-aa07ae5c9f47?auto=format&fit=crop&w=1200&q=80',
          caption: 'Orderly allées of linden trees and quiet arcades inside Jardin du Palais-Royal',
          category: 'Atmosphere',
          photoTip: 'Grab a flat white from Café Kitsuné to sip along the green benches.',
          credit: 'Unsplash / Paris Gardens',
        },
        tags: [
          { text: 'Tranquil Courtyard', type: 'highlight' },
          { text: 'Sculpture Garden', type: 'default' },
        ],
      },
      {
        id: 'eur-d5-p3',
        number: 3,
        globalNumber: 12,
        name: 'Place des Vosges & Le Marais Historic Walk',
        time: '17:00 – 20:00',
        description: 'Stroll Paris’s oldest planned square surrounded by symmetrical red-brick mansions, followed by warm falafel along Rue des Rosiers.',
        area: 'Le Marais (4th Arr.)',
        coordinates: { lat: 48.8555, lng: 2.3656 },
        photo: {
          url: 'https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?auto=format&fit=crop&w=1200&q=80',
          caption: 'Vaulted brick and limestone arcades framing the lawns of Place des Vosges',
          category: 'Heritage & Cafe',
          photoTip: 'Sit under the vaulted arcade near Victor Hugo’s former townhouse for atmospheric dusk light.',
          credit: 'Unsplash / Le Marais',
        },
        tags: [
          { text: 'Oldest Planned Square', type: 'highlight' },
          { text: 'L’As du Fallafel', type: 'default' },
        ],
      },
    ],
  },
  {
    id: 'day-6',
    dayNumber: 6,
    city: 'Paris',
    country: 'France',
    date: 'Day 6',
    title: 'Île de la Cité, Latin Quarter & Eiffel Twilight',
    subtitle: 'Sainte-Chapelle Stained Glass & Seine Banks',
    badge: 'Paris • Gothic & Iron Landmark',
    color: '#dc2626',
    polylineColor: '#dc2626',
    center: { lat: 48.8550, lng: 2.3250 },
    zoom: 13,
    googleMapsDirectionsUrl: 'https://www.google.com/maps/dir/?api=1&origin=Sainte-Chapelle&destination=Eiffel+Tower',
    places: [
      {
        id: 'eur-d6-p1',
        number: 1,
        globalNumber: 13,
        name: 'Sainte-Chapelle 13th-Century Stained Glass',
        time: '09:30 – 11:30',
        description: 'Gaze upward inside this jewel of Rayonnant Gothic architecture, where 15-meter tall stained-glass windows bathe the upper chapel in radiant violet light.',
        area: 'Île de la Cité',
        coordinates: { lat: 48.8554, lng: 2.3450 },
        photo: {
          url: 'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1200&q=80',
          caption: 'Jewel-like soaring stained glass panels illuminating the Gothic ribs of Sainte-Chapelle',
          category: 'Architecture',
          photoTip: 'Visit on a sunny morning between 10 AM and 11 AM when sunlight strikes the southern rose window.',
          credit: 'Unsplash / Sainte-Chapelle',
        },
        tags: [
          { text: 'Gothic Masterpiece', type: 'highlight' },
          { text: 'Cité Metro', type: 'default' },
        ],
      },
      {
        id: 'eur-d6-p2',
        number: 2,
        globalNumber: 14,
        name: 'Champ de Mars & Eiffel Tower Sparkling Lights',
        time: '19:30 – 22:00',
        description: 'Spread out a baguette, Comté cheese, and wine on the lawns of Champ de Mars to watch the Eiffel Tower ignite with 20,000 sparkling strobe lights on the hour.',
        area: '7th Arrondissement',
        coordinates: { lat: 48.8584, lng: 2.2945 },
        photo: {
          url: 'https://images.unsplash.com/photo-1431274172761-fca41d930114?auto=format&fit=crop&w=1200&q=80',
          caption: 'Gustave Eiffel’s wrought-iron lattice tower glowing against deep blue Parisian twilight',
          category: 'Architecture',
          photoTip: 'Cross the Pont d’Iéna to the Trocadéro esplanade for elevated symmetrical framing.',
          credit: 'Unsplash / Eiffel Tower',
        },
        tags: [
          { text: 'Sparkling Show', type: 'highlight' },
          { text: 'Iconic Evening', type: 'default' },
        ],
      },
    ],
  },
  {
    id: 'day-7',
    dayNumber: 7,
    city: 'Paris',
    country: 'France',
    date: 'Day 7',
    title: 'Musée d’Orsay Impressionism & Saint-Germain',
    subtitle: 'Monet, Van Gogh & Historic Literary Cafés',
    badge: 'Paris • Impressionism & Literature',
    color: '#dc2626',
    polylineColor: '#dc2626',
    center: { lat: 48.8599, lng: 2.3265 },
    zoom: 14,
    googleMapsDirectionsUrl: 'https://www.google.com/maps/dir/?api=1&origin=Musée+d’Orsay&destination=Jardin+du+Luxembourg',
    places: [
      {
        id: 'eur-d7-p1',
        number: 1,
        globalNumber: 15,
        name: 'Musée d’Orsay Railway Station Clock',
        time: '10:00 – 13:00',
        description: 'Housed in a spectacular Beaux-Arts railway terminal, examine the world’s foremost collection of Impressionist art from Monet, Degas, and Cézanne.',
        area: 'Left Bank (7th Arr.)',
        coordinates: { lat: 48.8599, lng: 2.3265 },
        photo: {
          url: 'https://images.unsplash.com/photo-1550340499-a6c60fc8287c?auto=format&fit=crop&w=1200&q=80',
          caption: 'Looking through the giant silhouette clock face overlooking Paris from Musée d’Orsay',
          category: 'Culture',
          photoTip: 'Head to the 5th floor café behind the giant station clock face for a famous silhouette shot.',
          credit: 'Unsplash / Musée d’Orsay',
        },
        tags: [
          { text: 'Impressionist Haven', type: 'highlight' },
          { text: 'Solferino Metro', type: 'default' },
        ],
      },
      {
        id: 'eur-d7-p2',
        number: 2,
        globalNumber: 16,
        name: 'Jardin du Luxembourg & Medici Fountain',
        time: '15:00 – 18:00',
        description: 'Relax in green iron chairs under chestnut groves, watching children navigate miniature wooden sailboats across the central basin.',
        area: 'Latin Quarter (6th Arr.)',
        coordinates: { lat: 48.8462, lng: 2.3371 },
        photo: {
          url: 'https://images.unsplash.com/photo-1509299349698-dd22323b5963?auto=format&fit=crop&w=1200&q=80',
          caption: 'The Italian Baroque grotto and tranquil reflection basin of the Fontaine Médicis',
          category: 'Atmosphere',
          photoTip: 'Walk to the northeastern corner near Rue de Vaugirard to discover the ivy-shrouded Medici Fountain.',
          credit: 'Unsplash / Luxembourg Gardens',
        },
        tags: [
          { text: 'Palace Gardens', type: 'highlight' },
          { text: 'Classic Green Chairs', type: 'default' },
        ],
      },
    ],
  },

  // --- TRANSIT ➔ AMSTERDAM (DAY 8) ---
  {
    id: 'day-8',
    dayNumber: 8,
    city: 'Transit ➔ Amsterdam',
    country: 'France / Netherlands',
    date: 'Day 8',
    title: 'Thalys / Eurostar Northward ➔ Amsterdam Canal Ring',
    subtitle: 'Gare du Nord to Amsterdam Centraal & Jordaan Walk',
    badge: 'Transit • Lowlands Rail',
    color: '#059669',
    polylineColor: '#059669',
    center: { lat: 52.3750, lng: 4.8850 },
    zoom: 14,
    googleMapsDirectionsUrl: 'https://www.google.com/maps/dir/?api=1&origin=Amsterdam+Centraal&destination=Jordaan',
    places: [
      {
        id: 'eur-d8-p1',
        number: 1,
        globalNumber: 17,
        name: 'Eurostar Direct: Paris to Amsterdam Centraal',
        time: '09:20 – 12:45',
        description: 'Ride across Belgian plains and Dutch polders directly into the Neo-Renaissance waterfront terminal of Amsterdam Centraal in 3 hours 20 mins.',
        area: 'Amsterdam Centraal',
        coordinates: { lat: 52.3791, lng: 4.9003 },
        photo: {
          url: 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=1200&q=80',
          caption: 'Gabled townhouses and tranquil water reflections along the historic Amsterdam canals',
          category: 'Architecture',
          photoTip: 'Step out of the Centraal Station south entrance directly into the canal boat docks.',
          credit: 'Unsplash / Amsterdam Rail',
        },
        tags: [
          { text: 'Direct High-Speed Rail', type: 'highlight' },
          { text: 'Central Waterfront', type: 'default' },
        ],
      },
      {
        id: 'eur-d8-p2',
        number: 2,
        globalNumber: 18,
        name: 'Jordaan Canal Bridges & Nine Streets (De Negen Straatjes)',
        time: '14:30 – 18:30',
        description: 'Wander picture-perfect humpback bridges lined with parked bicycles, specialty cheese boutiques, and cozy brown cafés serving warm apple pie.',
        area: 'Jordaan Canal Belt',
        coordinates: { lat: 52.3708, lng: 4.8828 },
        photo: {
          url: 'https://images.unsplash.com/photo-1512470876302-972faa2aa9a4?auto=format&fit=crop&w=1200&q=80',
          caption: 'Iconic Dutch bicycles locked to wrought-iron railings overlooking Prinsengracht',
          category: 'Atmosphere',
          photoTip: 'Stand on the intersection of Brouwersgracht and Prinsengracht for classic angled bridge views.',
          credit: 'Unsplash / Jordaan Canals',
        },
        tags: [
          { text: 'UNESCO Canal Belt', type: 'highlight' },
          { text: 'Winkel 43 Appeltaart', type: 'default' },
        ],
      },
    ],
  },

  // --- AMSTERDAM (DAYS 9-10) ---
  {
    id: 'day-9',
    dayNumber: 9,
    city: 'Amsterdam',
    country: 'Netherlands',
    date: 'Day 9',
    title: 'Museumplein Dutch Masters & Vondelpark',
    subtitle: 'Rijksmuseum, Van Gogh Museum & Sculpture Lawns',
    badge: 'Amsterdam • Dutch Golden Age',
    color: '#d97706', // amber-600
    polylineColor: '#d97706',
    center: { lat: 52.3590, lng: 4.8852 },
    zoom: 14,
    googleMapsDirectionsUrl: 'https://www.google.com/maps/dir/?api=1&origin=Rijksmuseum&destination=Vondelpark',
    places: [
      {
        id: 'eur-d9-p1',
        number: 1,
        globalNumber: 19,
        name: 'Rijksmuseum & Cuypers Library Passage',
        time: '09:30 – 13:00',
        description: 'Encounter Rembrandt’s monumental The Night Watch, Vermeer’s The Milkmaid, and step inside the four-story spiral staircase of the Cuypers Research Library.',
        area: 'Museumplein',
        coordinates: { lat: 52.3599, lng: 4.8852 },
        photo: {
          url: 'https://images.unsplash.com/photo-1584003564911-a7a321c84e1c?auto=format&fit=crop&w=1200&q=80',
          caption: 'Pierre Cuypers’ monumental 1885 brick museum facade framed above the Museumplein pool',
          category: 'Culture',
          photoTip: 'Walk through the public bicycle passage running directly through the center of the museum building.',
          credit: 'Unsplash / Rijksmuseum',
        },
        tags: [
          { text: 'Dutch Masters', type: 'highlight' },
          { text: 'Rembrandt Collection', type: 'default' },
        ],
      },
      {
        id: 'eur-d9-p2',
        number: 2,
        globalNumber: 20,
        name: 'Van Gogh Museum Masterpieces',
        time: '14:30 – 16:30',
        description: 'Follow Vincent van Gogh’s turbulent journey from dark rural Dutch sketches to incandescent French canvases of Sunflowers, Almond Blossom, and Bedroom in Arles.',
        area: 'Museumplein',
        coordinates: { lat: 52.3584, lng: 4.8811 },
        photo: {
          url: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1200&q=80',
          caption: 'Modern glass atrium leading into Vincent van Gogh’s chronological retrospective',
          category: 'Culture',
          photoTip: 'Reserve the earliest available afternoon slot well in advance as ticket entry is strictly timed.',
          credit: 'Unsplash / Van Gogh Arts',
        },
        tags: [
          { text: 'Sunflowers & Almond Blossom', type: 'highlight' },
          { text: 'Timed Entry Required', type: 'default' },
        ],
      },
      {
        id: 'eur-d9-p3',
        number: 3,
        globalNumber: 21,
        name: 'Vondelpark Cycling & Open-Air Pavilions',
        time: '17:00 – 19:30',
        description: 'Rent a traditional Dutch omafiets city bicycle to pedal winding tree-lined paths, passing willow-draped ponds and historic tearooms.',
        area: 'Oud-Zuid',
        coordinates: { lat: 52.3580, lng: 4.8686 },
        photo: {
          url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
          caption: 'Lush green lawns and weeping willow ponds winding through scenic Vondelpark',
          category: 'Nature & Skyline',
          photoTip: 'Stop at the Blauwe Theehuis (Blue Tea House), an iconic 1937 modernist circular pavilion.',
          credit: 'Unsplash / Dutch Parks',
        },
        tags: [
          { text: 'City Bike Loop', type: 'highlight' },
          { text: 'Blauwe Theehuis', type: 'default' },
        ],
      },
    ],
  },
  {
    id: 'day-10',
    dayNumber: 10,
    city: 'Amsterdam',
    country: 'Netherlands',
    date: 'Day 10',
    title: 'Historic Canal Cruise & De Pijp Farewell',
    subtitle: 'Golden Bend Waterways & Albert Cuyp Market',
    badge: 'Amsterdam • Grand Finale',
    color: '#d97706',
    polylineColor: '#d97706',
    center: { lat: 52.3570, lng: 4.8930 },
    zoom: 14,
    googleMapsDirectionsUrl: 'https://www.google.com/maps/dir/?api=1&origin=Albert+Cuyp+Market&destination=Herengracht',
    places: [
      {
        id: 'eur-d10-p1',
        number: 1,
        globalNumber: 22,
        name: 'Albert Cuyp Market & Fresh Stroopwafels',
        time: '10:00 – 12:30',
        description: 'The largest outdoor market in Europe in the bohemian De Pijp quarter. Watch piping-hot caramel pressed between freshly griddled cinnamon waffle biscuits.',
        area: 'De Pijp',
        coordinates: { lat: 52.3562, lng: 4.8942 },
        photo: {
          url: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=1200&q=80',
          caption: 'Steaming caramel spread over fresh griddled Dutch stroopwafels at the street stall',
          category: 'Culinary',
          photoTip: 'Order the XL warm stroopwafel from the Rudi’s stall located in the center of the market.',
          credit: 'Unsplash / Amsterdam Food',
        },
        tags: [
          { text: 'Fresh Stroopwafel', type: 'highlight' },
          { text: 'De Pijp Tram 24', type: 'default' },
        ],
      },
      {
        id: 'eur-d10-p2',
        number: 2,
        globalNumber: 23,
        name: 'Herengracht Golden Bend Historic Mansions',
        time: '14:00 – 16:00',
        description: 'Walk along the most prestigious curve of the canal ring (Gouden Bocht), lined with monumental 17th-century double-width merchant mansions.',
        area: 'Herengracht Canal',
        coordinates: { lat: 52.3644, lng: 4.8906 },
        photo: {
          url: 'https://images.unsplash.com/photo-1534351590666-13e3e96b5017?auto=format&fit=crop&w=1200&q=80',
          caption: 'Steep ornamental gables reflected in the glassy green waters of Herengracht',
          category: 'Architecture',
          photoTip: 'Look for the sandstone neck-gables and bell-gables displaying heraldic coats of arms.',
          credit: 'Unsplash / Amsterdam Architecture',
        },
        tags: [
          { text: 'Golden Age Mansions', type: 'highlight' },
          { text: 'Canal Ring Walk', type: 'default' },
        ],
      },
      {
        id: 'eur-d10-p3',
        number: 3,
        globalNumber: 24,
        name: 'Open-Boat Twilight Canal Cruise Farewell',
        time: '18:00 – 19:45',
        description: 'Cap off the 10-day grand journey gliding along illuminated illuminated bridges in a silent electric open boat with local cheeses and wines.',
        area: 'Prinsengracht Waterway',
        coordinates: { lat: 52.3685, lng: 4.8870 },
        photo: {
          url: 'https://images.unsplash.com/photo-1576941089067-2de3c901e126?auto=format&fit=crop&w=1200&q=80',
          caption: 'Arched stone canal bridges illuminated with amber bulbs reflecting across night waters',
          category: 'Atmosphere',
          photoTip: 'Choose an open-air salon boat instead of large enclosed tour barges for intimate water-level views.',
          credit: 'Unsplash / Night Canals',
        },
        tags: [
          { text: 'Electric Open Boat', type: 'highlight' },
          { text: 'Lit Bridges Tour', type: 'default' },
        ],
      },
    ],
  },
];

export const EUR_10D_DESTINATION: Destination = {
  meta: EUR_10D_META,
  days: EUR_10D_DAYS,
};
